# Change these first
owner: lensapp # Your GitHub organization or username, where this repository lives
repo: k8slens-status # The name of this repository

sites:
  - name: k8slens-api-docs
    url: https://api-docs.k8slens.dev
  - name: lenscloud-api
    url: https://api.k8slens.dev
  - name: lenscloud-app
    url: https://app.k8slens.dev
  - name: k8slens-docs
    url: https://docs.k8slens.dev
  - name: lenscloud-eu-bored
    url: https://eu.bored.k8slens.dev/healthz
  - name: lenscloud-survey
    url: https://survey.k8slens.dev/api
  - name: lenscloud-us-bored
    url: https://us.bored.k8slens.dev/healthz
  - name: k8slens-website
    url: https://k8slens.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.k8slens.dev
  # baseUrl: /demo-upptime
  logoUrl: https://raw.githubusercontent.com/lensapp/lens/master/docs/img/favicon.ico
  name: k8slens
  introTitle: "**Lens Cloud Service Status** "
  introMessage: This is the status page for all Lens cloud services
  navbar:
    - title: Status
      href: /
    - title: k8slens.dev
      href: https://k8slens.dev

assignees:
  - stevejr
  - JAtula
  
i18n:
  footer: Copyright ©2022 Mirantis Inc. - All rights reserved. 
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
