# Change these first
owner: lensapp # Your GitHub organization or username, where this repository lives
repo: k8slens-status # The name of this repository

sites:
  - name: api.k8slens.dev
    url: https://api.k8slens.dev
  - name: api-docs.k8slens.dev
    url: https://api-docs.k8slens.dev
  - name: app.k8slens.dev
    url: https://app.k8slens.dev/auth/realms/lensCloud/protocol/openid-connect/3p-cookies/step1.html
  - name: checkout.k8slens.dev
    url: https://checkout.k8slens.dev
    maxRedirects: 0
  - name: docs.k8slens.dev
    url: https://docs.k8slens.dev
  - name: downloads.k8slens.dev
    url: https://downloads.k8slens.dev/ide/latest.yml
  - name: eu.bored.k8slens.dev
    url: https://eu.bored.k8slens.dev/healthz
  - name: forums.k8slens.dev
    url: https://forums.k8slens.dev
  - name: k8slens.dev
    url: https://k8slens.dev
  - name: k8slens.zendesk.com
    url: https://k8slens.zendesk.com
    maxRedirects: 0
  - name: lenshq.io
    url: https://lenshq.io
  - name: survey.k8slens.dev
    url: https://survey.k8slens.dev/api
  - name: us.bored.k8slens.dev
    url: https://us.bored.k8slens.dev/healthz
  - name: v3.recurly.com
    url: https://v3.recurly.com/subscriptions
    headers:
    - "Accept: application/vnd.recurly.v2021-02-25"
    expectedStatusCodes:
    - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.k8slens.dev
  # baseUrl: /demo-upptime
  logoUrl: https://lenshq.io/images/lens-logo-icon.svg
  name: Lens
  introTitle: "**Lens Cloud Service Status**"
  introMessage: This is the status page for all Lens Cloud services
  navbar:
    - title: Status
      href: /
    - title: lenshq.io
      href: https://lenshq.io
  faviconSvg: https://lenshq.io/images/lens-logo-icon.svg
  
assignees:
  - stevejr

i18n:
  footer: Copyright ©2025 Mirantis Inc. - All rights reserved.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
